### ISSUE TITLE
A simple doubt in Pre Processing 

### ISSUE THREAD

**Issue by carankt** [ivanvovk/durian-pytorch#5]
First of all, great work on the repo! 
when I am reproducing the MFA output on LJSpeech, my number of samples is different than that of yours. 
I wanted to know if you applied any criteria to remove some data points in the pre-processing. 
Thanks in advance!

**Comment by ivanvovk** [comment]
Do you mean that your number of text grids produced by MFA differs from the number of given in my filelists (i.e. MFA missed some files)? To be honest, I don't remember what type of text preprocessing I have used... Probably, I have used [cleaners](https://github.com/NVIDIA/tacotron2/blob/master/text/cleaners.py) from NVIDIA Tacotron 2 repo. Moreover, note that MFA performance may differ from one tool's version to another.

**Comment by carankt** [comment]
LJSpeech originally has 13,100 samples. So there must be the same number of data points in your filelist.  But I am only getting 12,007.  
![image](https://user-images.githubusercontent.com/26355264/94153461-6f109d80-fe9a-11ea-9e1c-7b586e7853a9.png)

MFA does skip files if there exist words in the text that are not in the dictionary. 
Also the duration output in my mfa run is different than yours, presumming that might be because of different mfa version. Which version did you use while generating your filelist? 

Thanks for the quick response!

**Comment by ivanvovk** [comment]
Unfortunately, I haven't access anymore to the server, where I trained my model. Does it look totally different?

**Comment by ivanvovk** [comment]
Closing issue due inactivity.
